### ISSUE TITLE
bot

### ISSUE THREAD

**Issue by lLoki2022** [DinisIsaev/metin2-fishing-bot#1]
ran the file and nothing just stands you write more detailed how the script works on how much window to do is it necessary to transfer the bait to the button 1 or it just leave the inventory 
![image](https://github.com/user-attachments/assets/abbd90e8-2e2a-472b-903d-a2c359bdca35)

**Comment by DinisIsaev** [comment]
I have updated my read.me file, but from your image, I can see some fishes the metin I play doesn't have, therefore the bot will not open those fishes automatically.

**Comment by DinisIsaev** [comment]
Also, my bot automatically uses a mount to speed up fishing animations, so have one at hand, or just remove that part of the code.

**Comment by DinisIsaev** [comment]
If your metin has lag spikes consider putting a time.sleep between actions.
